[project]
name = "uk-carbon-intensity-mcp-py"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastmcp==2.12.2",
    "requests>=2.32.5",
]

[dependency-groups]
dev = [
    "types-requests>=2.32.4.20250809",
]
